repeat -name warn-starving -time 10 -timeUnits days -command [ warn-starving ]
repeat -name autonick -time 3 -timeUnits months -command [ autonick ]

repeat -name autoShearCreature -time 14 -timeUnits days -command [ workorder ShearCreature ]
repeat -name autoMilkCreature -time 14 -timeUnits days -command [ workorder "{\"job\":\"MilkCreature\",\"item_conditions\":[{\"condition\":\"AtLeast\",\"value\":2,\"flags\":[\"empty\"],\"item_type\":\"BUCKET\"}]}" ]

on-new-fortress ban-cooking booze; ban-cooking tallow; ban-cooking seeds; ban-cooking brew; ban-cooking mill; ban-cooking thread;
